name: Trigger downstream builds
on:
  workflow_call:
    secrets:
      token:
        required: true

jobs:
  trigger-dep-build:
    name: Trigger downstream builds
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        repo:
          - 'FasterXML/jackson-dataformats-binary'
          - 'FasterXML/jackson-dataformats-text'
          - 'FasterXML/jackson-dataformat-xml'

    steps:
      - name: Repository dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.token }}
          repository: ${{ matrix.repo }}
          event-type: jackson-databind-pushed
          # Could push information on what was built but not yet
          client-payload: '{"version": "N/A" }'
